steps:
# BUild the container image
# docker build -t imagename .
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/practical-link-469516-b7/docker-repo/python:v1', '.']
# Push the container image to registry
# docker push us-central1-docker.pkg.dev/practical-link-469516-b7/docker-repo/python:v1'
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/practical-link-469516-b7/docker-repo/python:v1']
# Deploy the container image to Cloud Run
# gcloud run deploy python-app --image us-central1-docker.pkg.dev/practical-link-469516-b7/docker-repo/python:v1', '--region', 'us-central1', '--allow-unauthenticated
# Deploy Container image to Cloudrun
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'python-app', '--image', '${_REGION}-docker.pkg.dev/practical-link-469516-b7/docker-repo/python:v1', '--region', 'us-central1', '--allow-unauthenticated']  
options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _REGION: us-central1
